### ISSUE TITLE
Leaflet starter appears broken

### ISSUE THREAD

**Issue by marksteven** [colbyfayock/gatsby-starter-leaflet#189]
Hi Colby,
Thanks for the advice earlier 
Have now tried to build site using your starter - terminal - mac 
Gatsby-cli 4.9.0
gatsby new gatsby-leaflet https://github.com/colbyfayock/gatsby-starter-leaflet.git

get these errors and load fails - Not sure if it is just me but does not appear to be working due to dependancy check potentially for everyone.

Hope this help
cheers Mark

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: gatsby-starter-leaflet@0.3.0
npm ERR! Found: gatsby@3.14.6
npm ERR! node_modules/gatsby
npm ERR!   gatsby@"^3.13.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer gatsby@"^2.0.0" from gatsby-plugin-react-leaflet@3.0.0
npm ERR! node_modules/gatsby-plugin-react-leaflet
npm ERR!   gatsby-plugin-react-leaflet@"3.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/me/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:

 ERROR 

Command failed with exit code 1: npm install

  Error: Command failed with exit code 1: npm install
  
  - error.js:60 makeError
    [global]/[gatsby-cli]/[execa]/lib/error.js:60:11
  
  - index.js:118 handlePromise
    [global]/[gatsby-cli]/[execa]/index.js:118:26
  
  - task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5
  
  - init-starter.js:135 install
    [global]/[gatsby-cli]/lib/init-starter.js:135:7
  
  - init-starter.js:202 clone
    [global]/[gatsby-cli]/lib/init-starter.js:202:3
  
  - init-starter.js:343 initStarter
    [global]/[gatsby-cli]/lib/init-starter.js:343:5
  
  - create-cli.js:460 
    [global]/[gatsby-cli]/lib/create-cli.js:460:9

**Comment by colbyfayock** [comment]
hey @marksteven what version of node are you using? I just ran it locally with no issues, I just tried with v14.17.1

**Comment by marksteven** [comment]
Hi Colby,
Thankyou for getting back to me.
On Mac (Bir Sur 11.6)(Intel) 
Visual Studio Code V1.65.2
node -v gives me v17.6.0
Gatsby-cli 4.9.1 (Just updated one step in case from 4.9.0)
so I'm a few in front of you it seems.
WIN is at 16.14.0 if your on WIN

As I write this I am giving it another go in case Ive done something dumb.

OK only took a couple of minutes.
It failed again.
Same error.
Seems to be looking for 0.3.0 but gets 3.14.6?
Not an error I have seen

Here is the full string 

gatsby new gatsby-testytwo https://github.com/colbyfayock/gatsby-starter-leaflet.git 
info Creating new site from git:
https://github.com/colbyfayock/gatsby-starter-leaflet.git

Cloning into 'gatsby-testytwo'...
remote: Enumerating objects: 89, done.
remote: Counting objects: 100% (89/89), done.
remote: Compressing objects: 100% (75/75), done.
remote: Total 89 (delta 0), reused 43 (delta 0), pack-reused 0
success Created starter directory layout
info Installing packages...

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: gatsby-starter-leaflet@0.3.0
npm ERR! Found: gatsby@3.14.6
npm ERR! node_modules/gatsby
npm ERR!   gatsby@"^3.13.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer gatsby@"^2.0.0" from gatsby-plugin-react-leaflet@3.0.0
npm ERR! node_modules/gatsby-plugin-react-leaflet
npm ERR!   gatsby-plugin-react-leaflet@"3.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/marksteven/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:

 ERROR 

Command failed with exit code 1: npm install



  Error: Command failed with exit code 1: npm install
  
  - error.js:60 makeError
    [global]/[gatsby-cli]/[execa]/lib/error.js:60:11
  
  - index.js:118 handlePromise
    [global]/[gatsby-cli]/[execa]/index.js:118:26
  
  - task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5
  
  - init-starter.js:135 install
    [global]/[gatsby-cli]/lib/init-starter.js:135:7
  
  - init-starter.js:202 clone
    [global]/[gatsby-cli]/lib/init-starter.js:202:3
  
  - init-starter.js:343 initStarter
    [global]/[gatsby-cli]/lib/init-starter.js:343:5
  
  - create-cli.js:460 
    [global]/[gatsby-cli]/lib/create-cli.js:460:9
  

Hope this helps
Regards
Mark

**Comment by colbyfayock** [comment]
weird so i can't reproduce on gatsby new but i can on develop

````
➜  gatsby-starter-leaflet git:(master) yarn develop
yarn run v1.22.18
warning ../../package.json: No license field
$ gatsby develop
warn Plugin gatsby-plugin-react-leaflet is not compatible with your gatsby version 3.13.0 - It requires gatsby@^2.0.0
warn Plugin gatsby-plugin-react-leaflet is not compatible with your gatsby version 3.13.0 - It requires gatsby@^2.0.0
success open and validate gatsby-configs, load plugins - 1.293s
success onPreInit - 0.030s
success initialize cache - 0.031s
success copy gatsby files - 0.101s
⠋ onPreBootstrap
⠋ Compiling Gatsby Functions
/Users/colbyfayock/Code/gatsby-starter-leaflet/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at BulkUpdateDecorator.hashFactory (/Users/colbyfayock/Code/gatsby-starter-leaflet/node_modules/webpack/lib/util/createHash.js:144:18)
    at BulkUpdateDecorator.digest (/Users/colbyfayock/Code/gatsby-starter-leaflet/node_modules/webpack/lib/util/createHash.js:79:21)
    at Compilation.createHash (/Users/colbyfayock/Code/gatsby-starter-leaflet/node_modules/webpack/lib/Compilation.js:3449:47)
    at /Users/colbyfayock/Code/gatsby-starter-leaflet/node_modules/webpack/lib/Compilation.js:2469:39
    at /Users/colbyfayock/Code/gatsby-starter-leaflet/node_modules/webpack/lib/Compilation.js:2670:5
    at Object.eachLimit (/Users/colbyfayock/Code/gatsby-starter-leaflet/node_modules/neo-async/async.js:3461:14)
    at Compilation._runCodeGenerationJobs (/Users/colbyfayock/Code/gatsby-starter-leaflet/node_modules/webpack/lib/Compilation.js:2632:12)
    at Compilation.codeGeneration (/Users/colbyfayock/Code/gatsby-starter-leaflet/node_modules/webpack/lib/Compilation.js:2618:8)
    at /Users/colbyfayock/Code/gatsby-starter-leaflet/node_modules/webpack/lib/Compilation.js:2454:11
    at Hook.eval [as callAsync] (eval at create (/Users/colbyfayock/Code/gatsby-starter-leaflet/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/colbyfayock/Code/gatsby-starter-leaflet/node_modules/tapable/lib/Hook.js:18:14)
    at /Users/colbyfayock/Code/gatsby-starter-leaflet/node_modules/webpack/lib/Compilation.js:2408:36
    at Hook.eval [as callAsync] (eval at create (/Users/colbyfayock/Code/gatsby-starter-leaflet/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/colbyfayock/Code/gatsby-starter-leaflet/node_modules/tapable/lib/Hook.js:18:14) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.9.0
error Command failed with exit code 7.
```


```
➜  gatsby-testytwo git:(main) gatsby develop
warn Plugin gatsby-plugin-react-leaflet is not compatible with your gatsby version 3.13.0 - It requires gatsby@^2.0.0
warn Plugin gatsby-plugin-react-leaflet is not compatible with your gatsby version 3.13.0 - It requires gatsby@^2.0.0
success open and validate gatsby-configs, load plugins - 1.277s
success onPreInit - 0.033s
success initialize cache - 0.028s
success copy gatsby files - 0.092s
⠋ onPreBootstrap
⠋ Compiling Gatsby Functions
/Users/colbyfayock/Code/gatsby-testytwo/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at BulkUpdateDecorator.hashFactory (/Users/colbyfayock/Code/gatsby-testytwo/node_modules/webpack/lib/util/createHash.js:144:18)
    at BulkUpdateDecorator.digest (/Users/colbyfayock/Code/gatsby-testytwo/node_modules/webpack/lib/util/createHash.js:79:21)
    at Compilation.createHash (/Users/colbyfayock/Code/gatsby-testytwo/node_modules/webpack/lib/Compilation.js:3449:47)
    at /Users/colbyfayock/Code/gatsby-testytwo/node_modules/webpack/lib/Compilation.js:2469:39
    at /Users/colbyfayock/Code/gatsby-testytwo/node_modules/webpack/lib/Compilation.js:2670:5
    at Object.eachLimit (/Users/colbyfayock/Code/gatsby-testytwo/node_modules/neo-async/async.js:3461:14)
    at Compilation._runCodeGenerationJobs (/Users/colbyfayock/Code/gatsby-testytwo/node_modules/webpack/lib/Compilation.js:2632:12)
    at Compilation.codeGeneration (/Users/colbyfayock/Code/gatsby-testytwo/node_modules/webpack/lib/Compilation.js:2618:8)
    at /Users/colbyfayock/Code/gatsby-testytwo/node_modules/webpack/lib/Compilation.js:2454:11
    at Hook.eval [as callAsync] (eval at create (/Users/colbyfayock/Code/gatsby-testytwo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/colbyfayock/Code/gatsby-testytwo/node_modules/tapable/lib/Hook.js:18:14)
    at /Users/colbyfayock/Code/gatsby-testytwo/node_modules/webpack/lib/Compilation.js:2408:36
    at Hook.eval [as callAsync] (eval at create (/Users/colbyfayock/Code/gatsby-testytwo/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/colbyfayock/Code/gatsby-testytwo/node_modules/tapable/lib/Hook.js:18:14) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.9.0
```
